version: '3.4'

services:
  rabbitmq.reciever.api:
    image: rabbitmqrecieverapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Rabbitmq.Reciever.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rabbitmq.reciever.api$
    volumes:
      - D:\Projects\RabbitMQ.DotnetCore\Rabbitmq.Reciever.Api:/app
      - C:\Users\Ahmed\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_rabbitmq.reciever.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rabbitmq.reciever.api$ \"bin/Debug/netcoreapp2.2/Rabbitmq.Reciever.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

  rabbitmq.sender.api:
    image: rabbitmqsenderapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Rabbitmq.Sender.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rabbitmq.sender.api$
    volumes:
      - D:\Projects\RabbitMQ.DotnetCore\Rabbitmq.Sender.Api:/app
      - C:\Users\Ahmed\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_rabbitmq.sender.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rabbitmq.sender.api$ \"bin/Debug/netcoreapp2.2/Rabbitmq.Sender.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

